
name: HTML CSS Deployment

# ================================
# Trigger (Workflow kab run hoga)
# ================================
on:
  
  push:
   
    branches:
      - main

# ================================
# Jobs Section
# ================================
jobs:
  
  deploy-website:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Setup Environment
        run: echo "Environment ready for deployment"


      - name: Deploy HTML & CSS Website
        uses: peaceiris/actions-gh-pages@v3
        with:
       
          github_token: ${{ secrets.GITHUB_TOKEN }}

          publish_dir: ./

      
      - name: Deployment Status
        run: echo "Website successfully deployed using GitHub Actions"
